version: '3.8'
services:
  # サーバーコンテナの作成
  web:
    build: .
    # コンテナ名の指定 PJごとに変更
    container_name: LIFF_demo
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs
    environment:
      # Netlifyトークン紐付け
      - NETLIFY_AUTH_TOKEN=nfp_D5UVRWCcZC2QioCNuc1BbnTLKQfQaRwR0a87
      # LIFF_ID
      - LIFF_ID=2002045846-Kdzee704


